import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/providers/storeProvider";
import { ToastContainer } from "react-toastify";

const geistJetBrainsMono = JetBrains_Mono({
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistJetBrainsMono.className} overflow-hidden antialiased`}
        >
          {children}
          <ToastContainer />
        </body>
      </html>
    </StoreProvider>
  );
}
