import type { Metadata } from "next";
import SideBar from "@/components/shared/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex">
      <SideBar />
      <main className="w-full pl-[300px]">{children}</main>
    </section>
  );
}
